language: node_js
os: linux
node_js:
  - "node"
before_install:
  - git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
  - git fetch
  - npm install -g yarn
install:
  - yarn
script:
  - yarn run importdata
  - yarn run prep
deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  local_dir: spectrum-css
  target_branch: test-pages
  skip_cleaup: true
  on:
    branch: nextjs
